image: python-bindings-compile

create_package:
  stage: deploy
  script:
    - python3 -m pip install conan
    - conan remote add gitlab ${CI_API_V4_URL}/projects/$CI_PROJECT_ID/packages/conan
    - conan remote list
    - CC=clang CXX=clang++ conan create . --build=missing -s compiler=clang -s compiler.version=15
    - CONAN_LOGIN_USERNAME=ci_user CONAN_PASSWORD=${CI_JOB_TOKEN} conan upload CppRO/0.0.2 --remote=gitlab --confirm

